import { defineConfig } from '@playwright/test';
import dotenv from 'dotenv';
import { existsSync } from 'fs';

// Load .env.local if it exists (generated by Convex)
if (existsSync('.env.local')) {
	dotenv.config({
		path: '.env.local',
		quiet: true
	});
}

export default defineConfig({
	webServer: {
		command: 'npm run build && npm run preview',
		port: 4173,
		reuseExistingServer: !process.env.CI
	},
	testDir: 'e2e',
	use: {
		baseURL: 'http://localhost:4173',
		trace: 'retain-on-failure'
	},
	retries: process.env.CI ? 2 : 0,
	outputDir: 'test-results'
});
